---
name: winblues7
description: Winblues 7

base-image: ghcr.io/ublue-os/bazzite-dx
image-version: latest

modules:
  - type: dnf
    repos:
      cleanup: true
      copr:
        enable:
          - bazzite-org/bazzite 
    install:
      packages:
      - kvantum
      - plymouth-plugin-script

  - type: script
    snippets:
      - 'cd $CONFIG_DIRECTORY/scripts && for script in *.sh; do [ -f "$script" ] && bash "$script" || exit $?; done'

  - type: files
    files:
      - source: system
        destination: /

  # Regenerate initramfs because of plymouth
  - type: initramfs

  - type: signing
