FROM ghcr.io/ublue-os/kinoite-main AS builder

# Install build dependencies
RUN dnf5 install -y gcc \
                    gcc-c++ \
                    cmake \
                    make \
                    extra-cmake-modules \
                    ninja-build \
                    plasma-workspace-devel \
                    libksysguard-devel \
                    unzip \
                    kvantum \
                    qt6-qtmultimedia-devel \
                    qt6-qt5compat-devel \
                    libplasma-devel \
                    qt6-qtbase-devel \
                    qt6-qtwayland-devel \
                    plasma-activities-devel \
                    kf6-kpackage-devel \
                    kf6-kglobalaccel-devel \
                    qt6-qtsvg-devel \
                    wayland-devel \
                    plasma-wayland-protocols \
                    kf6-ksvg-devel \
                    kf6-kcrash-devel \
                    kf6-kguiaddons-devel \
                    kf6-kcmutils-devel \
                    kf6-kio-devel \
                    kdecoration-devel \
                    kf6-ki18n-devel \
                    kf6-knotifications-devel \
                    kf6-kirigami-devel \
                    kf6-kiconthemes-devel \
                    gmp-ecm-devel \
                    kf5-plasma-devel \
                    libepoxy-devel \
                    kwin-devel \
                    kf6-karchive \
                    kf6-karchive-devel \
                    plasma-wayland-protocols-devel \
                    qt6-qtbase-private-devel \
                    qt6-qtbase-devel \
                    kf6-knewstuff-devel \
                    kf6-knotifyconfig-devel \
                    kf6-attica-devel \
                    kf6-krunner-devel \
                    kf6-kdbusaddons-devel \
                    kf6-sonnet-devel \
                    plasma5support-devel \
                    plasma-activities-stats-devel \
                    polkit-qt6-1-devel \
                    qt-devel \
                    libdrm-devel \
                    kf6-kitemmodels-devel \
                    kf6-kstatusnotifieritem-devel \
                    kf6-frameworkintegration-devel

# Build ATP
WORKDIR /build
RUN git clone https://gitgud.io/wackyideas/aerothemeplasma.git --depth 1
WORKDIR /build/aerothemeplasma

RUN mkdir -p /usr/local/share/mime/packages
RUN CMAKE_GENERATOR=Ninja bash install.sh --skip-x11

# Prepare required files
RUN mkdir -p /build/aerothemeplasma/system_files && \
    for manifest in /build/aerothemeplasma/manifest/*manifest.txt; do \
        while read -r file; do \
            mkdir -p "/build/aerothemeplasma/system_files/$(dirname "$file")" && \
            cp -r "$file" "/build/aerothemeplasma/system_files/$file"; \
        done < "$manifest"; \
    done

FROM scratch AS ctx
COPY --from=builder /build/aerothemeplasma/system_files /system_files
